# Importing/Reading Dataset

In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectPercentile   , chi2 
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import KFold
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import median_absolute_error
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

In [ ]:
file = "Student.xlsx"
#dataset = pd.read_excel(file)
missing_values = ["?"]
dataset = pd.read_excel(file, na_values=missing_values)

dataset = dataset.iloc[:,1:] #Student ID is defintely not relevant
y=dataset['RETURNED_2ND_YR'] 
dataset.drop('RETURNED_2ND_YR', inplace=True, axis=1)
X = dataset 

# PreProcessing



## Label Encoding

In [ ]:
from pandas.api.types import is_numeric_dtype
from sklearn.preprocessing import StandardScaler, LabelEncoder
X_col=list(X.columns)


for i in range(len(X_col)):
  if is_numeric_dtype(X[X_col[i]]) == False:
    X.iloc[:, i] = X.iloc[:, i].fillna('NaN')
    X[X_col[i]] = LabelEncoder().fit_transform(X[X_col[i]])
    


## Imputing/Splitting/Scaling Data

In [ ]:
ImputedModule = SimpleImputer(missing_values = np.nan, strategy ='most_frequent')
ImputedX = ImputedModule.fit(X)
X = ImputedX.transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 44)
from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

# Algorithms

## Logistic Regression
Bad Results  always given here.

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score , confusion_matrix
logreg = LogisticRegression(class_weight = 'balanced')
logreg.fit(X_train , y_train)
result= logreg.predict(X_test)
print('Logistic Regression accuracy score is',accuracy_score(y_test , result))
 
conf = confusion_matrix(y_test , result)
print('confusion matrix \n',  conf)


Logistic Regression accuracy score is 0.7735294117647059
confusion matrix 
 [[ 64  80]
 [ 74 462]]


## Support Vector Classifier
Results are somewhat decent.

In [ ]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV
parameters = {'kernel':('poly', 'rbf'), 'C':[0.5, 0.6, 0.4]}
svc = svm.SVC(gamma="auto")
clf = GridSearchCV(svc, parameters, cv=6)
clf.fit(X_train, y_train)



#Calculating Details
print('SVCModel Train Score is : ' , clf.score(X_train, y_train))
print('SVCModel Test Score is : ' , clf.score(X_test, y_test))
print('----------------------------------------------------')
y_pred = clf.predict(X_test)

#----------------------------------------------------
#Calculating Confusion Matrix
CM = confusion_matrix(y_test, y_pred)
print('Confusion Matrix is : \n', CM)





SVCModel Train Score is :  0.7871323529411764
SVCModel Test Score is :  0.788235294117647
----------------------------------------------------
Confusion Matrix is : 
 [[  0 144]
 [  0 536]]


## K-Nearest-Neigbors Classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
#KNNClassifierModel = KNeighborsClassifier(n_neighbors= 3,weights ='distance', # it can be distance
                                          #algorithm='auto') # it can be ball_tree, kd_tree,brute
#KNNClassifierModel.fit(X_train, y_train)




parameters = {'n_neighbors':[3, 4, 5], 'weights':('distance', 'uniform'), 'algorithm':('auto', 'ball_tree', 'kd_tree', 'brute')}
KNNClassifierModel = KNeighborsClassifier()
clf = GridSearchCV(KNNClassifierModel, parameters, cv=5)
clf.fit(X_train, y_train)




#Calculating Details
print('KNNClassifierModel Train Score is : ' , clf.score(X_train, y_train))
print('KNNClassifierModel Test Score is : ' , clf.score(X_test, y_test))
print('----------------------------------------------------')
y_pred = clf.predict(X_test)

#----------------------------------------------------
#Calculating Confusion Matrix
CM = confusion_matrix(y_test, y_pred)
print('Confusion Matrix is : \n', CM)

KNNClassifierModel Train Score is :  1.0
KNNClassifierModel Test Score is :  0.8147058823529412
----------------------------------------------------
Confusion Matrix is : 
 [[ 38 106]
 [ 20 516]]


## Naive Bayes

### Gaussian

In [ ]:
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()
clf.fit(X_train, y_train)
#Calculating Details
print('GaussianNB Train Score is : ' , clf.score(X_train, y_train))
print('GaussianNB Test Score is : ' , clf.score(X_test, y_test))
print('----------------------------------------------------')
y_pred = clf.predict(X_test)
#----------------------------------------------------
#Calculating Confusion Matrix
CM = confusion_matrix(y_test, y_pred)
print('Confusion Matrix is : \n', CM)

GaussianNB Train Score is :  0.7838235294117647
GaussianNB Test Score is :  0.21176470588235294
----------------------------------------------------
Confusion Matrix is : 
 [[144   0]
 [536   0]]


## Multinomial

In [ ]:

from sklearn.naive_bayes import MultinomialNB

MultinomialNBModel = MultinomialNB(alpha=1.0)
MultinomialNBModel.fit(X_train, y_train)

#Calculating Details
print('MultinomialNBModel Train Score is : ' , MultinomialNBModel.score(X_train, y_train))
print('MultinomialNBModel Test Score is : ' , MultinomialNBModel.score(X_test, y_test))
print('----------------------------------------------------')

#Calculating Prediction
y_pred = MultinomialNBModel.predict(X_test)
y_pred_prob = MultinomialNBModel.predict_proba(X_test)
#Calculating Confusion Matrix
CM = confusion_matrix(y_test, y_pred)
print('Confusion Matrix is : \n', CM)

MultinomialNBModel Train Score is :  0.7904411764705882
MultinomialNBModel Test Score is :  0.7867647058823529
----------------------------------------------------
Confusion Matrix is : 
 [[  0 144]
 [  1 535]]


### Complacent NB

In [ ]:
from sklearn.naive_bayes import ComplementNB
>>> clf = ComplementNB()
>>> clf.fit(X_train, y_train)
print('ComplementNB Train Score is : ' , clf.score(X_train, y_train))
print('ComplementNB Test Score is : ' , clf.score(X_test, y_test))
print('----------------------------------------------------')
y_pred = clf.predict(X_test)
#----------------------------------------------------
#Calculating Confusion Matrix
CM = confusion_matrix(y_test, y_pred)
print('Confusion Matrix is : \n', CM)

ComplementNB Train Score is :  0.7040441176470589
ComplementNB Test Score is :  0.7102941176470589
----------------------------------------------------
Confusion Matrix is : 
 [[ 78  66]
 [131 405]]


### Bernouli

In [ ]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(X_train, y_train)
print('BernoulliNB Train Score is : ' , clf.score(X_train, y_train))
print('BernoulliNB Test Score is : ' , clf.score(X_test, y_test))
print('----------------------------------------------------')
y_pred = clf.predict(X_test)
#----------------------------------------------------
#Calculating Confusion Matrix
CM = confusion_matrix(y_test, y_pred)
print('Confusion Matrix is : \n', CM)

BernoulliNB Train Score is :  0.7926470588235294
BernoulliNB Test Score is :  0.7676470588235295
----------------------------------------------------
Confusion Matrix is : 
 [[  5 139]
 [ 19 517]]


### Categorical Naive Bayes

In [ ]:
"""

from sklearn.naive_bayes import CategoricalNB
clf = CategoricalNB()
clf.fit(X_train, y_train)
print('CategoricalNB Train Score is : ' , clf.score(X_train, y_train))
#print('CategoricalNB Test Score is : ' , clf.score(X_test, y_test))
print('----------------------------------------------------')
y_pred = clf.predict(X_test)
#----------------------------------------------------
#Calculating Confusion Matrix
CM = confusion_matrix(y_test, y_pred)
print('Confusion Matrix is : \n', CM)
"""


CategoricalNB Train Score is :  0.7933823529411764
----------------------------------------------------


IndexError: ignored

## Linear Discriminant Analysis

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
LDAModel = LinearDiscriminantAnalysis(n_components=5,solver='svd',tol=0.0001)
LDAModel.fit(X_train, y_train)

#Calculating Details
print('LDAModel Train Score is : ' , LDAModel.score(X_train, y_train))
print('LDAModel Test Score is : ' , LDAModel.score(X_test, y_test))
print('----------------------------------------------------')

#Calculating Prediction
y_pred = LDAModel.predict(X_test)
y_pred_prob = LDAModel.predict_proba(X_test)
#---------------------------------------------------
#Calculating Confusion Matrix
CM = confusion_matrix(y_test, y_pred)
print('Confusion Matrix is : \n', CM)


## Quadratic Discriminant Analysis

In [ ]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
QDAModel = QuadraticDiscriminantAnalysis(tol=0.0001)
QDAModel.fit(X_train, y_train)

#Calculating Prediction
y_pred = QDAModel.predict(X_test)
y_pred_prob = QDAModel.predict_proba(X_test)

#Calculating Details
print('QDAModel Train Score is : ' , QDAModel.score(X_train, y_train))
print('QDAModel Test Score is : ' , QDAModel.score(X_test, y_test))

#----------------------------------------------------
#Calculating Confusion Matrix
CM = confusion_matrix(y_test, y_pred)
print('Confusion Matrix is : \n', CM)

## Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
DecisionTreeClassifierModel = DecisionTreeClassifier(criterion='gini',max_depth=4,random_state=33) #criterion can be entropy
DecisionTreeClassifierModel.fit(X_train, y_train)

#Calculating Details
print('DecisionTreeClassifierModel Train Score is : ' , DecisionTreeClassifierModel.score(X_train, y_train))
print('DecisionTreeClassifierModel Test Score is : ' , DecisionTreeClassifierModel.score(X_test, y_test))

#Calculating Prediction
y_pred = DecisionTreeClassifierModel.predict(X_test)
y_pred_prob = DecisionTreeClassifierModel.predict_proba(X_test)

#----------------------------------------------------
#Calculating Confusion Matrix
CM = confusion_matrix(y_test, y_pred)
print('Confusion Matrix is : \n', CM)


## Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RandomForestClassifierModel = RandomForestClassifier(criterion = 'entropy',n_estimators=100,max_depth=3,random_state=33) #criterion can be also : entropy 
RandomForestClassifierModel.fit(X_train, y_train)

#Calculating Details
print('RandomForestClassifierModel Train Score is : ' , RandomForestClassifierModel.score(X_train, y_train))
print('RandomForestClassifierModel Test Score is : ' , RandomForestClassifierModel.score(X_test, y_test))

#Calculating Prediction
y_pred = RandomForestClassifierModel.predict(X_test)
y_pred_prob = RandomForestClassifierModel.predict_proba(X_test)

#----------------------------------------------------
#Calculating Confusion Matrix
CM = confusion_matrix(y_test, y_pred)
print('Confusion Matrix is : \n', CM)
